export const citiesWithStreets: Record<string, string[]> = {
  gdansk: [
    'Dluga',
    'Mariacka',
    'Targowa',
    'Grunwaldzka',
    'Waly Jagiellonskie',
    'Hucisko',
    'Garncarska',
    'Rajska',
    'Chlebnicka',
    'Piwna',
  ],
  warszawa: [
    'Marszalkowska',
    'Nowy Swiat',
    'Krolewska',
    'Swietokrzyska',
    'Kasztanowa',
    'Malczewskiego',
    'Zielona',
    'Lipowa',
    'Jasna',
    'Cicha',
  ],
  poznan: [
    'Stary Rynek',
    'Wroclawska',
    'Polna',
    'Sikorskiego',
    'Kosciuszki',
    'Ogrodowa',
    'Sadowa',
    'Krucza',
    'Mickiewicza',
    'Kwiatowa',
  ],
};
